### ISSUE TITLE
IP delay on domain creation can cause failure

### ISSUE THREAD

**Issue by HartS** [r2d4/docker-machine-driver-kvm#1]
After starting a new domain, the driver [gets the domains IP](https://github.com/r2d4/docker-machine-driver-kvm/blob/b39972f3b556d1c4e6f211f31b0a3070cbc28e0b/pkg/kvm/kvm.go#L232-L235). Since the domain is newly created, the domain's interface on the driver-provisioned network may not have an IP yet, but that causes the IP lookup to fail with
```
E0502 19:55:25.461861       8 start.go:119] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: getting ip during machine start: getting IP: Could not find IP in Domain Interfaces.
```
The `getting ip during machine start` failure occurs when an error in getting the IP triggers a return instead of a retry: https://github.com/r2d4/docker-machine-driver-kvm/blob/b39972f3b556d1c4e6f211f31b0a3070cbc28e0b/pkg/kvm/kvm.go#L231-L240 

I was able to resolve this in my own deployment by changing

		ip, err := d.GetIP()
		if err != nil {
			return errors.Wrap(err, "getting ip during machine start")
		}
		if ip == "" {
			log.Debugf("Waiting for machine to come up %d/%d", i, 40)
			time.Sleep(3 * time.Second)
			continue
		}

to

		ip, err := d.GetIP()
		if ip == ""  || err != nil {
			log.Debugf("Waiting for machine to come up %d/%d", i, 40)
			time.Sleep(3 * time.Second)
			continue
		}
but I'm pretty green with Go, so I'm not sure if there's a more idiomatic way to handle the `Could not find IP in Domain Interfaces.` error from `GetIP()` selectively.

**Comment by r2d4** [comment]
Thanks for spotting this! I was just testing this on another machine (since my main workstation doesn't have a new enough version of libvirt). I will patch soon

**Comment by r2d4** [comment]
I don't think it was correct to throw an error in that case anyways.  I chose to just return an empty string and let the normal retry logic apply.

Fixed in https://github.com/r2d4/docker-machine-driver-kvm/commit/ba50f204ccf62c2f1f521fd60aa8eb68c39bcd2f
